### ISSUE TITLE
tihp yeah

### ISSUE THREAD

**Issue by Frinzie** [test0wanie/PyTDM#1]
tihp yeah dawssta yeah blawnt zshehh nehh mahm mawdoowoo "speech" (mawvah)

**Comment by ggegoge** [comment]
srawsoomiowehh, pshehss pshihpahdehk sahpehvnehh vshowehsh vehrss yeah dlah _iOS_ ssfawldehru _pythonista_.
Jak już uściślone zostało w readme musisz używać z `pyttsx3` nie na iOS.
sahmihkahm
